version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: attendance_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: attendance_system
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - attendance_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: attendance_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - attendance_network

  mcp-server-nodejs:
    build:
      context: ./mcp-server-nodejs
      dockerfile: Dockerfile
    container_name: attendance_mcp_server_nodejs
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: attendance_system
      NODE_ENV: production
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - attendance_network
    volumes:
      - mcp_logs:/app/logs
      - ./mcp-server-nodejs:/app

volumes:
  mysql_data:
    driver: local
  mcp_logs:
    driver: local

networks:
  attendance_network:
    driver: bridge